.TH DASHSPACE 1 "2024-01-15" "v1.0.0" "DashSpace CLI Manual"
.SH NAME
dashspace \- Official DashSpace CLI for creating and publishing modules
.SH SYNOPSIS
.B dashspace
[\fIOPTION\fR] \fICOMMAND\fR [\fIARGS\fR]
.SH DESCRIPTION
DashSpace CLI enables developers to create, test and publish modules for the DashSpace ecosystem.
.SH COMMANDS
.TP
.B login
Login to your DashSpace account
.TP
.B logout
Logout from DashSpace
.TP
.B whoami
Show current logged in user
.TP
.B create [name]
Create a new DashSpace module
.TP
.B preview
Open module in Buildy for preview
.TP
.B publish
Publish module to DashSpace store
.TP
.B search [query]
Search modules in the store
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help
.TP
.B \-v, \-\-version
Show version
.SH EXAMPLES
.TP
Create a new module:
.B dashspace create github-widget
.TP
Preview a module:
.B cd github-widget && dashspace preview
.TP
Publish a module:
.B dashspace publish
.SH AUTHOR
DashSpace Team <tech@dashspace.space>
.SH SEE ALSO
Full documentation available at https://docs.dashspace.dev/cli